dist: trusty
sudo: false
language: cpp

addons: 
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-7

script:
    - CXX=/usr/bin/g++-7 CC=/usr/bin/gcc-7 cmake -DNOU_BUILD_DOC=OFF -DNOU_BUILD_EXAMPLES=OFF -DNOU_BUILD_SHARED=OFF -DBUILD_TESTING=ON .
    - cmake --build . -- -j2
    - ctest
  